// <auto-generated />
namespace EfDbCoreFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class required_availability : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(required_availability));
        
        string IMigrationMetadata.Id
        {
            get { return "202402071626142_required_availability"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
